version: '2.1'
services:
  manabie-server:
    build: .
    ports:
      - 8989:8989/tcp
    environment:
      - "MANABIE_ENV=production"
      - "PORT=8989"
      - "GIN_MODE=release"
      - "MYSQL_DB_HOST=mariadb"
    depends_on:
      mariadb:
        condition: service_healthy
  mariadb:
    image: mariadb:10
    ports:
      - 3306:3306/tcp
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./resources/databases/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping"]
      timeout: 20s
      retries: 10


